# See https://fly.io/docs/reference/configuration/.

app = "awe"

[build]
  dockerfile = "demo/Dockerfile"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
