# Deploys demo to Heroku.
# MANUAL: Requires secret `HEROKU_API_KEY`.

name: Heroku app

on:
  # Enable manual trigger.
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build and deploy Heroku app
        run: |
          heroku container:login
          (cd demo && heroku container:push web --context-path .. \
            --app awe-demo --arg GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }})
          heroku container:release web --app awe-demo
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
